### PR TITLE
Added a few examples on how to use ODE.

### PR DESCRIPTION
**Pull request by YingboMa**
Duffing oscillator
Van der Pol oscillator

### CODE REVIEW

**Comment by obiajulu** [comment]
Great, I'll take a look at this by the end of the week.

**Comment by mauro3** [comment]
Very cool!  A few small comments:
- The notebook viewer at http://nbviewer.jupyter.org/ is much better (faster and more correct rendering) than githubs.  
- Don't use filenames with spaces. It just makes life difficult.  Use `-` or `_`.
- Are those velocity wobbles in the Pol-eq real?  Also only the driven Van der Pol oscillator is chaotic.
- I don't know how feasible it would be, but it would be cool to have sliders to change epsilon.  See https://github.com/JuliaLang/Interact.jl/blob/master/doc/notebooks/01-Introduction.ipynb.  But maybe you can spend your time better.

**Comment by mauro3** [comment]
Maybe the duffing needs a bit more prose explaining what you do.  Also when doing timings, it's best to run the function once first to get it JIT compiled.  Note that you only have to run it with the same argument types not the same values to get it JIT'ed, thus you could just run it for a small `tspan` to JIT and then do the timed run.

**Comment by obiajulu** [comment]
Yeah, for the duffing oscillator, may you could write a little more about the different solvers that you compare against each other. Why is one expected to have a better result than another, what methods do they use, etc.

And maybe for the vanderpol example, include a IVPTestSuite plot showing how well it solves the reference solution case. It could give the user a better idea of where IVPTestSuite fits into the ODE.jl work flow.

Overall, these are looking pretty solid. Maybe just go through them again as if it was your first time using ODE.jl, and add more explanations where you think a first time user would be a little confused.

**Comment by YingboMa** [comment]
@mauro3 Thanks a lot. It might be very hard to have sliders to change epsilon parameter, since ode23s will consume too much RAM. What do you think? By the way, how can I use notebook viewer in GitHub?

**Comment by mauro3** [comment]
Yeah, you're probably right, if it takes longer than a say 0.1s then sliders are not usable.

To use the jupyter viewer just past the file url: https://github.com/YingboMa/ODE.jl/blob/94c8f84762ced72610a4b53904fd731b4f280b86/examples/Duffing_oscillator.ipynb into the field in http://nbviewer.jupyter.org/ : http://nbviewer.jupyter.org/github/YingboMa/ODE.jl/blob/94c8f84762ced72610a4b53904fd731b4f280b86/examples/Duffing_oscillator.ipynb

**Pull request closed without merging**
